# Generated by Django 4.2.7 on 2024-01-18 14:28

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_litteruser_litteruser_id_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='litteruser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveIndex(
            model_name='litteruser',
            name='litteruser_usertag_idx',
        ),
        migrations.AlterField(
            model_name='litteruser',
            name='usertag',
            field=models.CharField(db_index=True, error_messages={'unique': 'A user with that usertag already exists.'}, max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='usertag'),
        ),
    ]
